#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi


sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get --assume-yes install libc6:i386 libncurses5:i386 libstdc++6:i386


#Install cmake 
rm cmake-3.21.1-linux-x86_64.sh
wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.sh
sudo sh cmake-3.21.1-linux-x86_64.sh --prefix=/usr/local --exclude-subdir --skip-license
rm cmake-3.21.1-linux-x86_64.sh

#Install for arm gcc compiler
sudo apt-get --assume-yes install zlib1g:i386

sudo snap install --classic code


#Update file:
echo -e "fs.inotify.max_user_watches=524288\n" >> /etc/sysctl.conf
sudo sysctl -p

#For UbieSimulator
sudo apt-get --assume-yes install libglib2.0.0:i386 libxext6:i386 libgl1-mesa-dev:i386 libdbus-1-3:i386 libxi6:i386 libsm6:i386 libfontconfig1:i386 libxrender1:i386


#Need this for gcc 4.8
echo -e "deb http://dk.archive.ubuntu.com/ubuntu/ xenial main\n" >> /etc/apt/sources.list
echo -e "deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe\n" >> /etc/apt/sources.list

sudo apt-get update

sudo apt-get --assume-yes install git
sudo apt-get --assume-yes install build-essential
sudo apt-get --assume-yes install gcc-4.8 g++-4.8
sudo apt-get --assume-yes install gcc-4.8-multilib g++-4.8-multilib

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/gcc-4.8 10
